version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true

branches:  
  only:
  - master

nuget:  
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet restore

after_build:
- dotnet pack "src\Narochno.Lambda.Slack\project.json" -c Release
